from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogIn(object):
    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(517, 564)
        font = QtGui.QFont()
        font.setPointSize(10)
        LogIn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Img/Images/logoicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LogIn.setWindowIcon(icon)
        LogIn.setStyleSheet("background-color: rgb(54, 57, 63);")
        self.gridLayout = QtWidgets.QGridLayout(LogIn)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(491, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.logo = QtWidgets.QLabel(LogIn)
        self.logo.setMinimumSize(QtCore.QSize(491, 101))
        self.logo.setMaximumSize(QtCore.QSize(491, 101))
        self.logo.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);\n"+"border-image: url(:/images/Logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        spacerItem1 = QtWidgets.QSpacerItem(491, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.usernamelabel = QtWidgets.QLabel(LogIn)
        self.usernamelabel.setMinimumSize(QtCore.QSize(401, 21))
        self.usernamelabel.setMaximumSize(QtCore.QSize(401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setObjectName("usernamelabel")
        self.horizontalLayout.addWidget(self.usernamelabel)
        spacerItem3 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.username = QtWidgets.QLineEdit(LogIn)
        self.username.setMinimumSize(QtCore.QSize(411, 41))
        self.username.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.username.setObjectName("username")
        self.horizontalLayout_2.addWidget(self.username)
        spacerItem5 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.passwordlabel = QtWidgets.QLabel(LogIn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setObjectName("passwordlabel")
        self.horizontalLayout_3.addWidget(self.passwordlabel)
        spacerItem7 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(28, 38, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.password = QtWidgets.QLineEdit(LogIn)
        self.password.setMinimumSize(QtCore.QSize(411, 41))
        self.password.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        spacerItem9 = QtWidgets.QSpacerItem(28, 38, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(21, 31, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.Forget = QtWidgets.QPushButton(LogIn)
        self.Forget.setMinimumSize(QtCore.QSize(151, 31))
        self.Forget.setMaximumSize(QtCore.QSize(151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Forget.setFont(font)
        self.Forget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Forget.setStyleSheet("background-color: rgb(54, 57, 63);\n"+"border-radius: 6;")
        self.Forget.setObjectName("Forget")
        self.horizontalLayout_5.addWidget(self.Forget)
        spacerItem11 = QtWidgets.QSpacerItem(51, 31, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.SignUp = QtWidgets.QPushButton(LogIn)
        self.SignUp.setMinimumSize(QtCore.QSize(93, 28))
        self.SignUp.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SignUp.setFont(font)
        self.SignUp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUp.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.SignUp.setObjectName("SignUp")
        self.horizontalLayout_5.addWidget(self.SignUp)
        self.login = QtWidgets.QPushButton(LogIn)
        self.login.setMinimumSize(QtCore.QSize(93, 28))
        self.login.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login.setFont(font)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.login.setObjectName("login")
        self.horizontalLayout_5.addWidget(self.login)
        spacerItem12 = QtWidgets.QSpacerItem(31, 31, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(491, 141, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem13)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "Log In"))
        self.usernamelabel.setText(_translate("LogIn", "Username"))
        self.passwordlabel.setText(_translate("LogIn", "  Password"))
        self.Forget.setText(_translate("LogIn", "Forget Password?"))
        self.SignUp.setText(_translate("LogIn", "Sign Up"))
        self.login.setText(_translate("LogIn", "Log In"))
import Images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogIn = QtWidgets.QDialog()
    ui = Ui_LogIn()
    ui.setupUi(LogIn)
    LogIn.show()
    sys.exit(app.exec_())
