from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(511, 621)
        signup.setMinimumSize(QtCore.QSize(511, 621))
        signup.setMaximumSize(QtCore.QSize(511, 621))
        font = QtGui.QFont()
        font.setPointSize(10)
        signup.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Img/Images/logoicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signup.setWindowIcon(icon)
        signup.setStyleSheet("background-color: rgb(54, 57, 63);")
        signup.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(signup)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(28, 468, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.namelabel = QtWidgets.QLabel(signup)
        self.namelabel.setMinimumSize(QtCore.QSize(401, 21))
        self.namelabel.setMaximumSize(QtCore.QSize(401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.namelabel.setFont(font)
        self.namelabel.setObjectName("namelabel")
        self.verticalLayout.addWidget(self.namelabel)
        self.name = QtWidgets.QLineEdit(signup)
        self.name.setMinimumSize(QtCore.QSize(411, 41))
        self.name.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usernamelabel = QtWidgets.QLabel(signup)
        self.usernamelabel.setMinimumSize(QtCore.QSize(401, 21))
        self.usernamelabel.setMaximumSize(QtCore.QSize(401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setObjectName("usernamelabel")
        self.verticalLayout_2.addWidget(self.usernamelabel)
        self.username = QtWidgets.QLineEdit(signup)
        self.username.setMinimumSize(QtCore.QSize(411, 41))
        self.username.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.username.setText("")
        self.username.setObjectName("username")
        self.verticalLayout_2.addWidget(self.username)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.passwordlabel = QtWidgets.QLabel(signup)
        self.passwordlabel.setMinimumSize(QtCore.QSize(401, 21))
        self.passwordlabel.setMaximumSize(QtCore.QSize(401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setObjectName("passwordlabel")
        self.verticalLayout_3.addWidget(self.passwordlabel)
        self.password = QtWidgets.QLineEdit(signup)
        self.password.setMinimumSize(QtCore.QSize(411, 41))
        self.password.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout_3.addWidget(self.password)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.repasswordlabel = QtWidgets.QLabel(signup)
        self.repasswordlabel.setMinimumSize(QtCore.QSize(411, 24))
        self.repasswordlabel.setMaximumSize(QtCore.QSize(411, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repasswordlabel.setFont(font)
        self.repasswordlabel.setObjectName("repasswordlabel")
        self.verticalLayout_4.addWidget(self.repasswordlabel)
        self.repassword = QtWidgets.QLineEdit(signup)
        self.repassword.setMinimumSize(QtCore.QSize(411, 41))
        self.repassword.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.repassword.setFont(font)
        self.repassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.repassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repassword.setObjectName("repassword")
        self.verticalLayout_4.addWidget(self.repassword)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SecQuecomboBox = QtWidgets.QComboBox(signup)
        self.SecQuecomboBox.setMinimumSize(QtCore.QSize(411, 31))
        self.SecQuecomboBox.setMaximumSize(QtCore.QSize(411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SecQuecomboBox.setFont(font)
        self.SecQuecomboBox.setStyleSheet("")
        self.SecQuecomboBox.setObjectName("SecQuecomboBox")
        self.SecQuecomboBox.addItem("")
        self.SecQuecomboBox.addItem("")
        self.SecQuecomboBox.addItem("")
        self.SecQuecomboBox.addItem("")
        self.SecQuecomboBox.addItem("")
        self.verticalLayout_5.addWidget(self.SecQuecomboBox)
        self.securityQue = QtWidgets.QLineEdit(signup)
        self.securityQue.setMinimumSize(QtCore.QSize(411, 41))
        self.securityQue.setMaximumSize(QtCore.QSize(411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.securityQue.setFont(font)
        self.securityQue.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        # self.securityQue.setEchoMode(QtWidgets.QLineEdit.Password)
        self.securityQue.setObjectName("securityQue")
        self.verticalLayout_5.addWidget(self.securityQue)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(28, 468, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(478, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.create = QtWidgets.QPushButton(signup)
        self.create.setMinimumSize(QtCore.QSize(93, 28))
        self.create.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create.setFont(font)
        self.create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create.setStyleSheet("background-color: rgb(255, 255, 255);\n"+"border-radius: 6;")
        self.create.setObjectName("create")
        self.horizontalLayout_2.addWidget(self.create)
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(478, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "Sign Up"))
        self.namelabel.setText(_translate("signup", "Name"))
        self.usernamelabel.setText(_translate("signup", "Username"))
        self.passwordlabel.setText(_translate("signup", "Password"))
        self.repasswordlabel.setText(_translate("signup", " Re-Password"))
        self.SecQuecomboBox.setItemText(0, _translate("signup", "Security Question?"))
        self.SecQuecomboBox.setItemText(1, _translate("signup", "Mother\'s Name"))
        self.SecQuecomboBox.setItemText(2, _translate("signup", "First Pet Name"))
        self.SecQuecomboBox.setItemText(3, _translate("signup", "First School Name"))
        self.SecQuecomboBox.setItemText(4, _translate("signup", "Set Passcode"))
        self.create.setText(_translate("signup", "Create"))
import Images_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    signup = QtWidgets.QDialog()
    ui = Ui_signup()
    ui.setupUi(signup)
    signup.show()
    sys.exit(app.exec_())
